# Generated by Django 5.1.2 on 2024-10-27 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescriptions',
            field=models.ManyToManyField(related_name='medicines', to='web.prescription'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='consumption_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.patients'),
        ),
    ]
