# Generated by Django 5.1.2 on 2024-10-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_prescription_medicines_medicine_prescriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.medicine'),
        ),
    ]
